# image name of Metasploit Docker Image 
image: harbor.cyber/cyber-range/metasploitframework/metasploit-framework
imagePullPolicy: Always # default: Always

serviceName: # leave it empty to generate a name based on helm release name and repo name
fullnameOverride: ""
nameOverride: ""

persistence:
  enabled: true
  storageClass: "" # StorageClass. If '' the default Storageclass is used.
  # claimName: # Existing claim, otherwise the default storage class is used.
  # accessMode: ReadWriteOnce #default: ReadWriteOnce
  size: 100Mi

msfvenom:
  path: "/usr/src/metasploit-framework/msfvenom"
  command: "" # command parameters for msfvenom. Do not use the '-o', this is part of the internal processing and will be added automatically.

