- name: Delete File
  hosts: '{{ host }}'
  vars:
    ansible_ssh_private_key_file: "{{ ssk_key | default(omit) }}"
    ansible_user: "{{ ssh_user | default(omit) }}"
    ansible_password: "{{ ssh_password | default(omit) }}"
    ansible_port: "{{ ssh_port | default(22,boolean=True) }}"
  tasks:

    - name: check if file exists
      stat:
        path: "{{ path }}"
      register: result

    - fail:
        msg: "{{ path }} not exists."
      when: result.stat.isreg is not defined

    - fail:
        msg: "{{ path }} is not a file or a symbolic link."
      when: not result.stat.isreg and not result.stat.islnk

    - name: delete file
      file:
        path: "{{ path }}"
        state: absent
