---
kind: "Service"
apiVersion: "v1"
metadata:
  labels:
    app.kubernetes.io/name: {{ template "dockermailserver.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  {{- if .Values.serviceName }}
  name: "{{ .Values.serviceName }}"
  {{- else }}
  name: {{ template "dockermailserver.fullname" . }}
  {{ end }}

spec:
  selector:
    app.kubernetes.io/name: {{ template "dockermailserver.fullname" . }}
    release: "{{ .Release.Name }}"
  type: ClusterIP

  ports:
    # Transfer
    - name: transfer
      port: 25
      targetPort: transfer
      protocol: TCP
    # ESMTP with implicit TLS
    - name: esmtp-implicit
      port: 465
      targetPort: esmtp-implicit
      protocol: TCP
    # ESMTP with explicit TLS (STARTTLS)
    - name: esmtp-explicit
      port: 587
      targetPort: esmtp-explicit
      protocol: TCP
    # IMAPS with implicit TLS
    - name: imap-implicit
      port: 993
      targetPort: imap-implicit
      protocol: TCP
    - name: imap-plain 
      port: 143
      targetPort: imap-plain
      protocol: TCP
