---
collections:
#  - name: awx.awx
#  - name: azure.azcollection
#  - name: amazon.aws
#  - name: theforeman.foreman
#  - name: google.cloud
#  - name: openstack.cloud
 # - name: community.vmware
#  - name: redhatinsights.insights

  - community.general
  - community.kubevirt
  - community.kubernetes
  - cloud.common
  - kubernetes.core
  - ovirt.ovirt
  - ansible.posix
  - cloud.common